### ISSUE TITLE
segfaults on invalid NULL record input

### ISSUE THREAD

**Issue by oerdnj** [dnstap/dnstap-ldns#1]
Found out by wrongly placing '#' sign:

```
dig +short @127.0.0.1 whoami.dnstap.info NULL# | dnstap-ldns -x 
```

ends with

```
Segmentation fault
```

**Comment by edmonds** [comment]
Hi, Ondrej:

Thanks very much for testing! This ought to be fixed in master now.

**Comment by oerdnj** [comment]
I have "broken" hands :), imagine the fear of my colleagues when I touch something...
